(function attachApiEndpointTools(global) {
  const DEFAULT_API_ENDPOINTS = Object.freeze({
    projectData: "/api/project-data",
    projectCenter: "/api/project-center",
    createProject: "/api/create-project",
    openProject: "/api/open-project",
    undoProjectHistory: "/api/undo-project-history",
    redoProjectHistory: "/api/redo-project-history",
    restoreProjectHistory: "/api/restore-project-history",
    createProjectHistorySnapshot: "/api/create-project-history-snapshot",
    previewProjectHistoryRestore: "/api/preview-project-history-restore",
    updateProjectHistorySnapshot: "/api/update-project-history-snapshot",
    acknowledgeProjectRecoveryNotice: "/api/acknowledge-project-recovery-notice",
    renameProject: "/api/rename-project",
    duplicateProject: "/api/duplicate-project",
    deleteProject: "/api/delete-project",
    saveScene: "/api/save-scene",
    createScene: "/api/create-scene",
    exportBuild: "/api/export-build",
    importAssets: "/api/import-assets",
    generateOpenAiAsset: "/api/generate-openai-asset",
    createVoicePlaceholder: "/api/create-voice-placeholder",
    createVoicePlaceholders: "/api/create-voice-placeholders",
    matchVoiceFiles: "/api/match-voice-files",
    saveProjectSettings: "/api/save-project-settings",
    importLocalizationPatches: "/api/import-localization-patches",
    repairProjectDoctor: "/api/repair-project-doctor",
    renameVariable: "/api/rename-variable",
    createChapter: "/api/create-chapter",
    createStarterKit: "/api/create-starter-kit",
    duplicateChapter: "/api/duplicate-chapter",
    renameScene: "/api/rename-scene",
    renameChapter: "/api/rename-chapter",
    deleteScene: "/api/delete-scene",
    moveScene: "/api/move-scene",
    moveChapter: "/api/move-chapter",
    deleteChapter: "/api/delete-chapter",
    duplicateScene: "/api/duplicate-scene",
    replaceAsset: "/api/replace-asset",
    deleteAsset: "/api/delete-asset",
    updateAssetMeta: "/api/update-asset-meta",
    updateCharacterPresentation: "/api/update-character-presentation",
    bulkUpdateAssetTags: "/api/bulk-update-asset-tags",
    bulkDeleteAssets: "/api/bulk-delete-assets",
    creativeAssistant: "/api/creative-assistant",
  });

  const API_ENDPOINTS = Object.freeze({
    ...DEFAULT_API_ENDPOINTS,
    generateOpenAiAsset:
      global.CanvasiaEditorOpenAiAssetGenerator?.API_GENERATE_OPENAI_ASSET ??
      DEFAULT_API_ENDPOINTS.generateOpenAiAsset,
  });

  function getApiEndpoint(key, fallback = "") {
    return API_ENDPOINTS[String(key ?? "")] ?? fallback;
  }

  global.CanvasiaEditorApiEndpoints = Object.freeze({
    DEFAULT_API_ENDPOINTS,
    API_ENDPOINTS,
    getApiEndpoint,
    API_PROJECT_DATA: API_ENDPOINTS.projectData,
    API_PROJECT_CENTER: API_ENDPOINTS.projectCenter,
    API_CREATE_PROJECT: API_ENDPOINTS.createProject,
    API_OPEN_PROJECT: API_ENDPOINTS.openProject,
    API_UNDO_PROJECT_HISTORY: API_ENDPOINTS.undoProjectHistory,
    API_REDO_PROJECT_HISTORY: API_ENDPOINTS.redoProjectHistory,
    API_RESTORE_PROJECT_HISTORY: API_ENDPOINTS.restoreProjectHistory,
    API_CREATE_PROJECT_HISTORY_SNAPSHOT: API_ENDPOINTS.createProjectHistorySnapshot,
    API_PREVIEW_PROJECT_HISTORY_RESTORE: API_ENDPOINTS.previewProjectHistoryRestore,
    API_UPDATE_PROJECT_HISTORY_SNAPSHOT: API_ENDPOINTS.updateProjectHistorySnapshot,
    API_ACKNOWLEDGE_PROJECT_RECOVERY_NOTICE: API_ENDPOINTS.acknowledgeProjectRecoveryNotice,
    API_RENAME_PROJECT: API_ENDPOINTS.renameProject,
    API_DUPLICATE_PROJECT: API_ENDPOINTS.duplicateProject,
    API_DELETE_PROJECT: API_ENDPOINTS.deleteProject,
    API_SAVE_SCENE: API_ENDPOINTS.saveScene,
    API_CREATE_SCENE: API_ENDPOINTS.createScene,
    API_EXPORT_BUILD: API_ENDPOINTS.exportBuild,
    API_IMPORT_ASSETS: API_ENDPOINTS.importAssets,
    API_GENERATE_OPENAI_ASSET: API_ENDPOINTS.generateOpenAiAsset,
    API_CREATE_VOICE_PLACEHOLDER: API_ENDPOINTS.createVoicePlaceholder,
    API_CREATE_VOICE_PLACEHOLDERS: API_ENDPOINTS.createVoicePlaceholders,
    API_MATCH_VOICE_FILES: API_ENDPOINTS.matchVoiceFiles,
    API_SAVE_PROJECT_SETTINGS: API_ENDPOINTS.saveProjectSettings,
    API_IMPORT_LOCALIZATION_PATCHES: API_ENDPOINTS.importLocalizationPatches,
    API_REPAIR_PROJECT_DOCTOR: API_ENDPOINTS.repairProjectDoctor,
    API_RENAME_VARIABLE: API_ENDPOINTS.renameVariable,
    API_CREATE_CHAPTER: API_ENDPOINTS.createChapter,
    API_CREATE_STARTER_KIT: API_ENDPOINTS.createStarterKit,
    API_DUPLICATE_CHAPTER: API_ENDPOINTS.duplicateChapter,
    API_RENAME_SCENE: API_ENDPOINTS.renameScene,
    API_RENAME_CHAPTER: API_ENDPOINTS.renameChapter,
    API_DELETE_SCENE: API_ENDPOINTS.deleteScene,
    API_MOVE_SCENE: API_ENDPOINTS.moveScene,
    API_MOVE_CHAPTER: API_ENDPOINTS.moveChapter,
    API_DELETE_CHAPTER: API_ENDPOINTS.deleteChapter,
    API_DUPLICATE_SCENE: API_ENDPOINTS.duplicateScene,
    API_REPLACE_ASSET: API_ENDPOINTS.replaceAsset,
    API_DELETE_ASSET: API_ENDPOINTS.deleteAsset,
    API_UPDATE_ASSET_META: API_ENDPOINTS.updateAssetMeta,
    API_UPDATE_CHARACTER_PRESENTATION: API_ENDPOINTS.updateCharacterPresentation,
    API_BULK_UPDATE_ASSET_TAGS: API_ENDPOINTS.bulkUpdateAssetTags,
    API_BULK_DELETE_ASSETS: API_ENDPOINTS.bulkDeleteAssets,
    API_CREATIVE_ASSISTANT: API_ENDPOINTS.creativeAssistant,
  });
})(typeof window !== "undefined" ? window : globalThis);
