// Shared visual-effect, particle, save, and UI preset constants for the exported web runtime.
// Keep this module data-only so player.js stays focused on orchestration.

export const PARTICLE_PRESET_LABELS = {
  snow: "雪花",
  rain: "雨丝",
  petals: "樱花",
  dust: "光尘",
  embers: "火星",
  sparkles: "闪光",
  bubbles: "气泡",
  confetti: "纸片",
  smoke: "烟雾",
  flame: "火焰",
  stardust: "星尘",
  glyphs: "法阵符纹",
};

export const PARTICLE_INTENSITY_LABELS = {
  light: "轻一点",
  medium: "中等",
  heavy: "浓一点",
};

export const PARTICLE_SPEED_LABELS = {
  slow: "慢一点",
  medium: "正常",
  fast: "快一点",
};

export const PARTICLE_WIND_LABELS = {
  left: "向左吹",
  still: "几乎无风",
  right: "向右吹",
};

export const PARTICLE_AREA_LABELS = {
  full: "铺满全屏",
  left: "左半边",
  center: "中间区域",
  right: "右半边",
};

export const PARTICLE_BLEND_LABELS = {
  screen: "滤色发光",
  add: "线性发光",
  normal: "正常叠加",
};

export const PARTICLE_EMISSION_MODE_LABELS = {
  continuous: "持续发射",
  burst: "爆发式发射",
};

export const PARTICLE_EMITTER_SHAPE_LABELS = {
  line: "线形发射器",
  point: "点发射器",
  box: "盒形发射器",
  circle: "圆形发射器",
};

export const PARTICLE_FOLLOW_LABELS = {
  none: "固定在画面上",
  character: "跟随当前说话角色",
  camera: "跟随镜头中心",
};

export const PARTICLE_FOLLOW_ANCHOR_LABELS = {
  head: "头部附近",
  torso: "身体中段",
  feet: "脚边 / 地面",
};

export const PARTICLE_SIZE_CURVE_LABELS = {
  steady: "尺寸保持稳定",
  bloom: "先小后大",
  shrink: "慢慢缩小",
  pulse: "中段放大",
};

export const PARTICLE_OPACITY_CURVE_LABELS = {
  fade: "正常淡出",
  linger: "停留更久",
  blink: "中段更亮",
  pop: "先亮后淡",
};

export const PARTICLE_COLOR_CURVE_LABELS = {
  steady: "颜色保持稳定",
  cool_shift: "慢慢偏冷",
  warm_shift: "越烧越暖",
  spectral: "光谱漂移",
  pulse_glow: "中段爆亮",
};

export const PARTICLE_FORCE_FIELD_LABELS = {
  none: "无中心力场",
  attract: "吸附中心",
  repel: "排斥中心",
  orbit: "环绕中心",
};

export const PARTICLE_CUSTOM_COMBO_LAYER_LIMIT = 6;

export const PARTICLE_COMBO_PRESET_LABELS = {
  none: "单层粒子",
  blizzard_stack: "暴风雪叠层",
  inferno_stack: "火焰仪式叠层",
  arcane_stack: "魔法阵叠层",
  celestial_stack: "星海梦境叠层",
  celebration_stack: "礼花舞台叠层",
};

export const PARTICLE_PRESET_DEFAULTS = {
  snow: {
    density: 40,
    sizeMin: 6,
    sizeMax: 18,
    lifeMin: 6,
    lifeMax: 11,
    gravityX: 0,
    gravityY: 70,
    gravityZ: 16,
    spreadX: 100,
    spreadY: 22,
    spreadZ: 36,
    opacityMin: 0.38,
    opacityMax: 0.95,
    rotationMin: 0,
    rotationMax: 180,
    spin: 55,
    turbulence: 22,
    color: "#ffffff",
    colorAccent: "#dff4ff",
    blend: "screen",
  },
  rain: {
    density: 56,
    sizeMin: 2,
    sizeMax: 4,
    lifeMin: 1.2,
    lifeMax: 2.5,
    gravityX: 18,
    gravityY: 190,
    gravityZ: -8,
    spreadX: 100,
    spreadY: 14,
    spreadZ: 20,
    opacityMin: 0.26,
    opacityMax: 0.82,
    rotationMin: 8,
    rotationMax: 14,
    spin: 0,
    turbulence: 10,
    color: "#b7dcff",
    colorAccent: "#f0fbff",
    blend: "screen",
  },
  petals: {
    density: 28,
    sizeMin: 12,
    sizeMax: 22,
    lifeMin: 4.5,
    lifeMax: 8.2,
    gravityX: 0,
    gravityY: 58,
    gravityZ: 6,
    spreadX: 100,
    spreadY: 24,
    spreadZ: 42,
    opacityMin: 0.48,
    opacityMax: 0.96,
    rotationMin: -20,
    rotationMax: 40,
    spin: 120,
    turbulence: 36,
    color: "#ffd6ea",
    colorAccent: "#fff3f8",
    blend: "screen",
  },
  dust: {
    density: 26,
    sizeMin: 4,
    sizeMax: 12,
    lifeMin: 5.5,
    lifeMax: 11,
    gravityX: 0,
    gravityY: 24,
    gravityZ: 24,
    spreadX: 100,
    spreadY: 40,
    spreadZ: 70,
    opacityMin: 0.18,
    opacityMax: 0.72,
    rotationMin: 0,
    rotationMax: 360,
    spin: 40,
    turbulence: 24,
    color: "#c4f6ff",
    colorAccent: "#f8fdff",
    blend: "screen",
  },
  embers: {
    density: 24,
    sizeMin: 3,
    sizeMax: 9,
    lifeMin: 2.6,
    lifeMax: 6.4,
    gravityX: 6,
    gravityY: -46,
    gravityZ: 30,
    spreadX: 100,
    spreadY: 36,
    spreadZ: 54,
    opacityMin: 0.3,
    opacityMax: 0.92,
    rotationMin: 0,
    rotationMax: 180,
    spin: 80,
    turbulence: 34,
    color: "#ffb36b",
    colorAccent: "#fff1b5",
    blend: "add",
  },
  sparkles: {
    density: 18,
    sizeMin: 5,
    sizeMax: 12,
    lifeMin: 1.8,
    lifeMax: 4.2,
    gravityX: 0,
    gravityY: 16,
    gravityZ: 36,
    spreadX: 100,
    spreadY: 50,
    spreadZ: 58,
    opacityMin: 0.28,
    opacityMax: 1,
    rotationMin: 0,
    rotationMax: 180,
    spin: 180,
    turbulence: 26,
    color: "#dff8ff",
    colorAccent: "#8fe8ff",
    blend: "add",
  },
  bubbles: {
    density: 20,
    sizeMin: 10,
    sizeMax: 26,
    lifeMin: 3.8,
    lifeMax: 8.6,
    gravityX: 0,
    gravityY: -72,
    gravityZ: 28,
    spreadX: 100,
    spreadY: 44,
    spreadZ: 64,
    opacityMin: 0.18,
    opacityMax: 0.62,
    rotationMin: -16,
    rotationMax: 16,
    spin: 36,
    turbulence: 18,
    color: "#b6f3ff",
    colorAccent: "#effcff",
    blend: "normal",
  },
  confetti: {
    density: 34,
    sizeMin: 6,
    sizeMax: 14,
    lifeMin: 3.2,
    lifeMax: 6.4,
    gravityX: 0,
    gravityY: 120,
    gravityZ: 18,
    spreadX: 100,
    spreadY: 26,
    spreadZ: 48,
    opacityMin: 0.52,
    opacityMax: 0.98,
    rotationMin: 0,
    rotationMax: 360,
    spin: 240,
    turbulence: 42,
    color: "#7fe7ff",
    colorAccent: "#ff8ee3",
    blend: "normal",
  },
  smoke: {
    density: 22,
    sizeMin: 24,
    sizeMax: 64,
    lifeMin: 4.6,
    lifeMax: 10.8,
    gravityX: 0,
    gravityY: -24,
    gravityZ: 42,
    spreadX: 72,
    spreadY: 44,
    spreadZ: 80,
    opacityMin: 0.14,
    opacityMax: 0.46,
    rotationMin: -26,
    rotationMax: 26,
    spin: 18,
    turbulence: 32,
    color: "#aebed4",
    colorAccent: "#f1f7ff",
    blend: "normal",
  },
  flame: {
    density: 26,
    sizeMin: 14,
    sizeMax: 34,
    lifeMin: 1.4,
    lifeMax: 3.8,
    gravityX: 0,
    gravityY: -82,
    gravityZ: 24,
    spreadX: 40,
    spreadY: 36,
    spreadZ: 44,
    opacityMin: 0.34,
    opacityMax: 0.92,
    rotationMin: -18,
    rotationMax: 18,
    spin: 58,
    turbulence: 44,
    color: "#ff8b3d",
    colorAccent: "#fff4a6",
    blend: "add",
  },
  stardust: {
    density: 30,
    sizeMin: 3,
    sizeMax: 10,
    lifeMin: 5.4,
    lifeMax: 12.6,
    gravityX: 0,
    gravityY: 8,
    gravityZ: 54,
    spreadX: 100,
    spreadY: 60,
    spreadZ: 90,
    opacityMin: 0.18,
    opacityMax: 0.86,
    rotationMin: 0,
    rotationMax: 240,
    spin: 140,
    turbulence: 28,
    color: "#8edbff",
    colorAccent: "#fff1ff",
    blend: "screen",
  },
  glyphs: {
    density: 14,
    sizeMin: 18,
    sizeMax: 36,
    lifeMin: 2.6,
    lifeMax: 5.8,
    gravityX: 0,
    gravityY: 0,
    gravityZ: 18,
    spreadX: 34,
    spreadY: 18,
    spreadZ: 26,
    opacityMin: 0.34,
    opacityMax: 0.92,
    rotationMin: -12,
    rotationMax: 12,
    spin: 120,
    turbulence: 14,
    color: "#85d4ff",
    colorAccent: "#f7dcff",
    blend: "add",
  },
};

export const PARTICLE_PRESET_ADVANCED_DEFAULTS = {
  snow: {
    emissionMode: "continuous",
    emitterShape: "line",
    emitterX: 50,
    emitterY: -6,
    emitterZ: 0,
    attractionX: 0,
    attractionY: 0,
    vortex: 12,
    follow: "none",
    sizeCurve: "steady",
    opacityCurve: "linger",
    forceField: "none",
    fieldX: 50,
    fieldY: 52,
  },
  rain: {
    emissionMode: "continuous",
    emitterShape: "line",
    emitterX: 50,
    emitterY: -8,
    emitterZ: -8,
    attractionX: 10,
    attractionY: 0,
    vortex: 6,
    follow: "none",
    sizeCurve: "steady",
    opacityCurve: "fade",
    forceField: "none",
    fieldX: 50,
    fieldY: 58,
  },
  petals: {
    emissionMode: "continuous",
    emitterShape: "line",
    emitterX: 50,
    emitterY: -4,
    emitterZ: 10,
    attractionX: 0,
    attractionY: 4,
    vortex: 48,
    follow: "none",
    sizeCurve: "pulse",
    opacityCurve: "linger",
    forceField: "orbit",
    fieldX: 50,
    fieldY: 56,
  },
  dust: {
    emissionMode: "continuous",
    emitterShape: "box",
    emitterX: 50,
    emitterY: 52,
    emitterZ: 20,
    attractionX: 0,
    attractionY: -4,
    vortex: 18,
    follow: "none",
    sizeCurve: "bloom",
    opacityCurve: "linger",
    forceField: "attract",
    fieldX: 50,
    fieldY: 54,
  },
  embers: {
    emissionMode: "continuous",
    emitterShape: "circle",
    emitterX: 50,
    emitterY: 104,
    emitterZ: 24,
    attractionX: 0,
    attractionY: -14,
    vortex: 65,
    follow: "none",
    sizeCurve: "shrink",
    opacityCurve: "pop",
    forceField: "orbit",
    fieldX: 50,
    fieldY: 84,
  },
  sparkles: {
    emissionMode: "burst",
    emitterShape: "point",
    emitterX: 50,
    emitterY: 48,
    emitterZ: 0,
    attractionX: 0,
    attractionY: 0,
    vortex: 95,
    follow: "none",
    sizeCurve: "pulse",
    opacityCurve: "blink",
    forceField: "orbit",
    fieldX: 50,
    fieldY: 50,
  },
  bubbles: {
    emissionMode: "continuous",
    emitterShape: "circle",
    emitterX: 50,
    emitterY: 106,
    emitterZ: 26,
    attractionX: 0,
    attractionY: -18,
    vortex: 24,
    follow: "none",
    sizeCurve: "bloom",
    opacityCurve: "linger",
    forceField: "attract",
    fieldX: 50,
    fieldY: 36,
  },
  confetti: {
    emissionMode: "burst",
    emitterShape: "line",
    emitterX: 50,
    emitterY: -6,
    emitterZ: 6,
    attractionX: 0,
    attractionY: 16,
    vortex: 110,
    follow: "none",
    sizeCurve: "pulse",
    opacityCurve: "pop",
    forceField: "repel",
    fieldX: 50,
    fieldY: 46,
  },
  smoke: {
    emissionMode: "continuous",
    emitterShape: "circle",
    emitterX: 50,
    emitterY: 94,
    emitterZ: 22,
    attractionX: 0,
    attractionY: -10,
    vortex: 36,
    follow: "none",
    sizeCurve: "bloom",
    opacityCurve: "linger",
    forceField: "attract",
    fieldX: 50,
    fieldY: 58,
  },
  flame: {
    emissionMode: "continuous",
    emitterShape: "point",
    emitterX: 50,
    emitterY: 94,
    emitterZ: 12,
    attractionX: 0,
    attractionY: -22,
    vortex: 84,
    follow: "none",
    sizeCurve: "shrink",
    opacityCurve: "pop",
    forceField: "orbit",
    fieldX: 50,
    fieldY: 76,
  },
  stardust: {
    emissionMode: "continuous",
    emitterShape: "box",
    emitterX: 50,
    emitterY: 48,
    emitterZ: 36,
    attractionX: 0,
    attractionY: 0,
    vortex: 72,
    follow: "camera",
    sizeCurve: "pulse",
    opacityCurve: "blink",
    forceField: "orbit",
    fieldX: 50,
    fieldY: 50,
  },
  glyphs: {
    emissionMode: "burst",
    emitterShape: "circle",
    emitterX: 50,
    emitterY: 56,
    emitterZ: 10,
    attractionX: 0,
    attractionY: 0,
    vortex: 150,
    follow: "character",
    sizeCurve: "pulse",
    opacityCurve: "blink",
    forceField: "orbit",
    fieldX: 50,
    fieldY: 56,
  },
};

export const PARTICLE_COMBO_PRESET_CONFIGS = {
  none: [],
  blizzard_stack: [
    {
      preset: "snow",
      densityMultiplier: 0.84,
      layerCount: 2,
      sizeScale: 1.08,
      lifeScale: 1.12,
      spreadYMultiplier: 1.18,
      spreadZAdd: 18,
      turbulenceAdd: 10,
      opacityScale: 0.92,
      follow: "camera",
      followAnchor: "torso",
      blend: "screen",
      colorMix: 0.28,
    },
    {
      preset: "dust",
      densityMultiplier: 0.42,
      sizeScale: 1.52,
      lifeScale: 1.34,
      spreadYMultiplier: 1.46,
      spreadZAdd: 24,
      gravityYAdd: -10,
      turbulenceAdd: 18,
      opacityScale: 0.46,
      follow: "camera",
      followAnchor: "torso",
      forceField: "attract",
      blend: "screen",
      color: "#d9efff",
      colorAccent: "#ffffff",
      colorEnd: "#b8d8ff",
    },
  ],
  inferno_stack: [
    {
      preset: "flame",
      densityMultiplier: 0.88,
      layerCount: 2,
      sizeScale: 1.04,
      opacityScale: 0.96,
      follow: "character",
      followAnchor: "feet",
      emitterYOffset: 10,
      blend: "add",
      colorMix: 0.36,
    },
    {
      preset: "smoke",
      densityMultiplier: 0.44,
      sizeScale: 1.62,
      lifeScale: 1.26,
      spreadYMultiplier: 1.38,
      spreadZAdd: 28,
      gravityYAdd: -14,
      turbulenceAdd: 14,
      opacityScale: 0.56,
      follow: "character",
      followAnchor: "torso",
      emitterYOffset: 4,
      blend: "normal",
      color: "#9e95a6",
      colorAccent: "#ddd8e8",
      colorEnd: "#706978",
    },
    {
      preset: "embers",
      densityMultiplier: 0.48,
      sizeScale: 0.92,
      lifeScale: 0.92,
      opacityScale: 0.78,
      follow: "character",
      followAnchor: "torso",
      emitterYOffset: 8,
      blend: "add",
      colorMix: 0.22,
    },
  ],
  arcane_stack: [
    {
      preset: "glyphs",
      densityMultiplier: 0.9,
      layerCount: 2,
      sizeScale: 1.06,
      opacityScale: 0.92,
      follow: "character",
      followAnchor: "feet",
      forceField: "orbit",
      blend: "add",
      colorMix: 0.48,
    },
    {
      preset: "stardust",
      densityMultiplier: 0.54,
      sizeScale: 0.92,
      lifeScale: 1.12,
      spreadZAdd: 34,
      turbulenceAdd: 18,
      opacityScale: 0.72,
      follow: "camera",
      followAnchor: "torso",
      area: "center",
      blend: "screen",
      colorMix: 0.52,
    },
    {
      preset: "sparkles",
      densityMultiplier: 0.34,
      sizeScale: 0.82,
      opacityScale: 0.78,
      emissionMode: "burst",
      follow: "character",
      followAnchor: "torso",
      emitterShape: "circle",
      blend: "add",
      colorMix: 0.48,
    },
  ],
  celestial_stack: [
    {
      preset: "stardust",
      densityMultiplier: 0.88,
      layerCount: 2,
      opacityScale: 0.92,
      follow: "camera",
      followAnchor: "torso",
      blend: "screen",
      colorMix: 0.46,
    },
    {
      preset: "dust",
      densityMultiplier: 0.4,
      sizeScale: 1.44,
      lifeScale: 1.28,
      spreadZAdd: 30,
      opacityScale: 0.42,
      turbulenceAdd: 18,
      follow: "camera",
      followAnchor: "torso",
      blend: "screen",
      colorMix: 0.44,
    },
    {
      preset: "bubbles",
      densityMultiplier: 0.24,
      sizeScale: 0.74,
      lifeScale: 1.12,
      gravityYAdd: -22,
      opacityScale: 0.36,
      follow: "camera",
      followAnchor: "torso",
      area: "center",
      blend: "normal",
      colorMix: 0.34,
    },
  ],
  celebration_stack: [
    {
      preset: "confetti",
      densityMultiplier: 0.78,
      layerCount: 2,
      emissionMode: "burst",
      opacityScale: 0.96,
      blend: "normal",
      colorMix: 0.3,
    },
    {
      preset: "sparkles",
      densityMultiplier: 0.4,
      sizeScale: 0.82,
      opacityScale: 0.82,
      emissionMode: "burst",
      blend: "add",
      colorMix: 0.44,
    },
    {
      preset: "stardust",
      densityMultiplier: 0.26,
      lifeScale: 0.92,
      opacityScale: 0.46,
      follow: "camera",
      followAnchor: "torso",
      blend: "screen",
      colorMix: 0.38,
    },
  ],
};

export const PARTICLE_IMAGE_ASSET_TYPES = ["background", "sprite", "cg", "ui"];

export const SHAKE_INTENSITY_LABELS = {
  light: "轻微",
  medium: "明显",
  heavy: "很强",
};

export const EFFECT_DURATION_LABELS = {
  short: "短一下",
  medium: "正常",
  long: "久一点",
};

export const TRANSITION_DURATION_DEFAULT_MS = 360;
export const TRANSITION_DURATION_MIN_MS = 0;
export const TRANSITION_DURATION_MAX_MS = 5000;

export const FLASH_COLOR_LABELS = {
  white: "白闪",
  warm: "暖光",
  red: "红闪",
  black: "黑闪",
};

export const FLASH_INTENSITY_LABELS = {
  soft: "柔和",
  medium: "明显",
  strong: "很亮",
};

export const FADE_ACTION_LABELS = {
  fade_out: "慢慢淡出",
  fade_in: "慢慢亮起",
};

export const FADE_COLOR_LABELS = {
  black: "黑场",
  white: "白场",
};

export const MUSIC_END_MODE_LABELS = {
  until_next_music: "播到下一首或停止卡",
  scene_end: "播完整个场景",
  after_block: "播到指定卡片后",
};

export const CAMERA_ZOOM_ACTION_LABELS = {
  zoom_in: "推近镜头",
  zoom_out: "拉远镜头",
  reset: "恢复正常",
};

export const CAMERA_ZOOM_STRENGTH_LABELS = {
  light: "轻一点",
  medium: "明显",
  heavy: "更强",
};

export const CAMERA_ZOOM_FOCUS_LABELS = {
  left: "看左侧",
  center: "看中间",
  right: "看右侧",
};

export const SCREEN_FILTER_ACTION_LABELS = {
  apply: "开启滤镜",
  clear: "关闭滤镜",
};

export const SCREEN_FILTER_PRESET_LABELS = {
  memory: "暖色回忆",
  mono: "黑白回忆",
  dream: "梦境柔光",
  cold: "冷色回放",
};

export const SCREEN_FILTER_STRENGTH_LABELS = {
  soft: "轻一点",
  medium: "正常",
  strong: "更明显",
};

export const SCREEN_COLOR_GRADE_DEFAULTS = Object.freeze({
  brightness: 100,
  contrast: 100,
  saturation: 100,
  hue: 0,
  temperature: 0,
  vignette: 0,
});

export const SCREEN_COLOR_GRADE_LIMITS = Object.freeze({
  brightness: Object.freeze([40, 180]),
  contrast: Object.freeze([40, 180]),
  saturation: Object.freeze([0, 220]),
  hue: Object.freeze([-180, 180]),
  temperature: Object.freeze([-100, 100]),
  vignette: Object.freeze([0, 100]),
});

export const CAMERA_PAN_TARGET_LABELS = {
  left: "向左看",
  center: "回到中间",
  right: "向右看",
};

export const CAMERA_PAN_STRENGTH_LABELS = {
  light: "轻一点",
  medium: "明显",
  heavy: "更远",
};

export const DEPTH_BLUR_ACTION_LABELS = {
  apply: "开启景深",
  clear: "关闭景深",
};

export const DEPTH_BLUR_FOCUS_LABELS = {
  left: "左侧角色更清楚",
  center: "中间角色更清楚",
  right: "右侧角色更清楚",
  full: "只虚化背景",
};

export const DEPTH_BLUR_STRENGTH_LABELS = {
  soft: "轻一点",
  medium: "正常",
  strong: "更明显",
};

export const VIDEO_FIT_LABELS = {
  contain: "完整显示",
  cover: "铺满裁切",
  fill: "拉伸填满",
};

export const CREDITS_BACKGROUND_LABELS = {
  dark: "深色电影片尾",
  light: "浅色清爽片尾",
  transparent: "叠在当前画面上",
};

export const SAVE_SHORTCUT_COUNT = 3;
export const SAVE_DIALOG_PAGE_SIZE = 6;
export const DEFAULT_PROJECT_DIALOG_BOX_CONFIG = {
  preset: "moonlight",
  shape: "rounded",
  widthPercent: 76,
  minHeight: 148,
  paddingX: 18,
  paddingY: 14,
  backgroundColor: "#0c1422",
  backgroundOpacity: 92,
  borderColor: "#79dcff",
  borderOpacity: 18,
  textColor: "#f3f6ff",
  speakerColor: "#ffffff",
  hintColor: "#c8d6ea",
  blurStrength: 10,
  borderWidth: 1,
  shadowStrength: 30,
  panelAssetId: "",
  panelAssetOpacity: 0,
  panelAssetFit: "cover",
  anchor: "bottom",
  offsetXPercent: 0,
  offsetYPercent: 0,
};
export const DEFAULT_PROJECT_GAME_UI_CONFIG = {
  preset: "stellar",
  layoutPreset: "balanced",
  titleLayout: "center",
  fontStyle: "modern",
  surfaceStyle: "glass",
  brandMode: "project",
  sidePanelMode: "full",
  sidePanelPosition: "right",
  topbarPosition: "top",
  hudPosition: "top",
  titleCardAnchor: "center",
  titleCardOffsetXPercent: 0,
  titleCardOffsetYPercent: 0,
  layoutGap: 20,
  sidePanelWidth: 320,
  backgroundColor: "#071120",
  backgroundAccentColor: "#6bd5ff",
  panelColor: "#0c1422",
  panelOpacity: 88,
  textColor: "#f3f7ff",
  mutedTextColor: "#bacce4",
  accentColor: "#79dcff",
  accentAltColor: "#7b7cff",
  buttonTextColor: "#f8fcff",
  borderColor: "#79dcff",
  borderOpacity: 18,
  cornerRadius: 22,
  backdropBlur: 14,
  stageVignette: 42,
  motionIntensity: 70,
  titleBackgroundAssetId: "",
  titleBackgroundFit: "cover",
  titleBackgroundOpacity: 42,
  titleLogoAssetId: "",
  panelFrameAssetId: "",
  panelFrameOpacity: 18,
  panelFrameSlice: { top: 24, right: 24, bottom: 24, left: 24 },
  buttonFrameAssetId: "",
  buttonHoverFrameAssetId: "",
  buttonPressedFrameAssetId: "",
  buttonDisabledFrameAssetId: "",
  buttonFrameOpacity: 24,
  buttonFrameSlice: { top: 18, right: 18, bottom: 18, left: 18 },
  saveSlotFrameAssetId: "",
  systemPanelFrameAssetId: "",
  uiOverlayAssetId: "",
  uiOverlayOpacity: 8,
};
export const PROJECT_GAME_UI_PRESETS = {
  stellar: DEFAULT_PROJECT_GAME_UI_CONFIG,
  warm: {
    preset: "warm",
    layoutPreset: "balanced",
    titleLayout: "center",
    fontStyle: "rounded",
    surfaceStyle: "glass",
    brandMode: "project",
    sidePanelMode: "full",
    sidePanelPosition: "right",
    topbarPosition: "top",
    hudPosition: "top",
    titleCardAnchor: "center",
    titleCardOffsetXPercent: 0,
    titleCardOffsetYPercent: 0,
    layoutGap: 20,
    sidePanelWidth: 320,
    backgroundColor: "#fff4e8",
    backgroundAccentColor: "#f0a35f",
    panelColor: "#fff8ef",
    panelOpacity: 92,
    textColor: "#3d2a1f",
    mutedTextColor: "#7a6252",
    accentColor: "#d67245",
    accentAltColor: "#f0b35d",
    buttonTextColor: "#fffaf4",
    borderColor: "#d67245",
    borderOpacity: 20,
    cornerRadius: 24,
    backdropBlur: 10,
    stageVignette: 28,
    motionIntensity: 45,
    titleBackgroundOpacity: 36,
    titleBackgroundFit: "cover",
    panelFrameOpacity: 14,
    buttonFrameOpacity: 18,
    uiOverlayOpacity: 5,
  },
  paper: {
    preset: "paper",
    layoutPreset: "compact",
    titleLayout: "left",
    fontStyle: "serif",
    surfaceStyle: "solid",
    brandMode: "project",
    sidePanelMode: "compact",
    sidePanelPosition: "left",
    topbarPosition: "top",
    hudPosition: "bottom-left",
    titleCardAnchor: "left",
    titleCardOffsetXPercent: 0,
    titleCardOffsetYPercent: 0,
    layoutGap: 16,
    sidePanelWidth: 280,
    backgroundColor: "#f7efe0",
    backgroundAccentColor: "#b98a5d",
    panelColor: "#fff9ed",
    panelOpacity: 96,
    textColor: "#3d2a1d",
    mutedTextColor: "#806b57",
    accentColor: "#9a683d",
    accentAltColor: "#c09a64",
    buttonTextColor: "#fffaf1",
    borderColor: "#a5794e",
    borderOpacity: 28,
    cornerRadius: 12,
    backdropBlur: 4,
    stageVignette: 35,
    motionIntensity: 25,
    titleBackgroundOpacity: 28,
    titleBackgroundFit: "cover",
    panelFrameOpacity: 22,
    buttonFrameOpacity: 12,
    uiOverlayOpacity: 10,
  },
  minimal: {
    preset: "minimal",
    layoutPreset: "minimal",
    titleLayout: "poster",
    fontStyle: "modern",
    surfaceStyle: "minimal",
    brandMode: "hidden",
    sidePanelMode: "hidden",
    sidePanelPosition: "right",
    topbarPosition: "hidden",
    hudPosition: "hidden",
    titleCardAnchor: "bottom",
    titleCardOffsetXPercent: 0,
    titleCardOffsetYPercent: -6,
    layoutGap: 14,
    sidePanelWidth: 260,
    backgroundColor: "#05070c",
    backgroundAccentColor: "#ffffff",
    panelColor: "#05070c",
    panelOpacity: 48,
    textColor: "#f7f7f7",
    mutedTextColor: "#c6c8cf",
    accentColor: "#ffffff",
    accentAltColor: "#aeb5c6",
    buttonTextColor: "#101216",
    borderColor: "#ffffff",
    borderOpacity: 16,
    cornerRadius: 10,
    backdropBlur: 2,
    stageVignette: 20,
    motionIntensity: 10,
    titleBackgroundOpacity: 24,
    titleBackgroundFit: "cover",
    panelFrameOpacity: 0,
    buttonFrameOpacity: 0,
    uiOverlayOpacity: 0,
  },
};
export const PROJECT_DIALOG_BOX_PRESETS = {
  moonlight: {
    preset: "moonlight",
    shape: "rounded",
    widthPercent: 76,
    minHeight: 148,
    paddingX: 18,
    paddingY: 14,
    backgroundColor: "#0c1422",
    backgroundOpacity: 92,
    borderColor: "#79dcff",
    borderOpacity: 18,
    textColor: "#f3f6ff",
    speakerColor: "#ffffff",
    hintColor: "#c8d6ea",
    blurStrength: 10,
    borderWidth: 1,
    shadowStrength: 30,
    panelAssetOpacity: 0,
    panelAssetFit: "cover",
    anchor: "bottom",
    offsetXPercent: 0,
    offsetYPercent: 0,
  },
  warm: {
    preset: "warm",
    shape: "rounded",
    widthPercent: 76,
    minHeight: 148,
    paddingX: 16,
    paddingY: 14,
    backgroundColor: "#fffaf5",
    backgroundOpacity: 92,
    borderColor: "#8f6548",
    borderOpacity: 18,
    textColor: "#332117",
    speakerColor: "#7f5438",
    hintColor: "#6d5b4f",
    blurStrength: 8,
    borderWidth: 1,
    shadowStrength: 18,
    panelAssetOpacity: 0,
    panelAssetFit: "cover",
    anchor: "bottom",
    offsetXPercent: 0,
    offsetYPercent: 0,
  },
  paper: {
    preset: "paper",
    shape: "square",
    widthPercent: 76,
    minHeight: 156,
    paddingX: 18,
    paddingY: 16,
    backgroundColor: "#fff7e8",
    backgroundOpacity: 95,
    borderColor: "#b08659",
    borderOpacity: 28,
    textColor: "#4a2f1d",
    speakerColor: "#7f5438",
    hintColor: "#7f6a54",
    blurStrength: 4,
    borderWidth: 1,
    shadowStrength: 16,
    panelAssetOpacity: 0,
    panelAssetFit: "cover",
    anchor: "bottom",
    offsetXPercent: 0,
    offsetYPercent: 0,
  },
  transparent: {
    preset: "transparent",
    shape: "capsule",
    widthPercent: 88,
    minHeight: 132,
    paddingX: 14,
    paddingY: 10,
    backgroundColor: "#08111b",
    backgroundOpacity: 0,
    borderColor: "#7fe6ff",
    borderOpacity: 0,
    textColor: "#f4f8ff",
    speakerColor: "#ffffff",
    hintColor: "#d0daf0",
    blurStrength: 0,
    borderWidth: 0,
    shadowStrength: 0,
    panelAssetOpacity: 0,
    panelAssetFit: "cover",
    anchor: "bottom",
    offsetXPercent: 0,
    offsetYPercent: 0,
  },
};
